### PR TITLE
Setting up various badges for the repository

### PR DESCRIPTION
**Pull request by cmacmackin**
This commit will add badges for CI status, code coverage, etc. to the repository README. It will also update the CI system a bit. It is still a work-in-progress.

### CODE REVIEW

**Comment by makeclean** [comment]
This is all good stuff, but we should be moving stuff to use INL's CI system CIVET which is much more integrated with MOOSE development and when developemen tis further along will be ran by INL to make sure they don' t break app

**Comment by cmacmackin** [comment]
In the task for this PR it says to include badges for "Dependency (for MFEM)". What is meant by this? The version we depend on? At present I think we're still depending on a particular commit of a fork, so that doesn't really apply.

**Comment by cmacmackin** [comment]
I've added all of the badges I can think of at the moment. I often like to put in a badge for the status of building/deploying documentation, but we can think about that once some has been written.

**Review by alexanderianblair — APPROVED** [review]
Thanks Chris - this looks good, and should help with reporting code quality of new commits going forward.

Happy for this to go in as-is; minor comment to trim the cclake build script is optional and could be implemented in a later PR.

**Pull request merged**
