### PR TITLE
Fix directory path in makefile

### PR DESCRIPTION
**Pull request by nmnobre**

### CODE REVIEW

**Comment by alexanderianblair** [comment]
This is currently causing the Docker build to fail as Platypus can no longer find the header files in `mfem/miniapps/common`

**Comment by nmnobre** [comment]
> This is currently causing the Docker build to fail in this PR as Platypus can no longer find the header files in `mfem/miniapps/common`. The original path is correct, although the `mfem/miniapps/common` include directory could be referenced more cleanly to avoid confusion

How odd... Is `miniapps` not alongside `config`? Also, for the libraries you point to `$(MFEM_DIR)/miniapps/common` which is where I'd expect things to be?...

**Comment by alexanderianblair** [comment]
The miniapps headers (of which we are using `common`) are not installed by MFEM when built, and so are not found in `mfem/build`, although the libraries are

**Comment by nmnobre** [comment]
> The miniapps headers (of which we are using `common`) are not installed by MFEM when built, and so are not found in `mfem/build`, although the libraries are - the libraries are automatically copied during build.

Okay, makes sense, a fix for upstream MFEM then, not platypus...

**Comment by nmnobre** [comment]
For future reference, we're assuming that we built/installed MFEM in a sub-directory of the mfem repo root directory. This is obviously not great, but it's the best we can do at the moment, unless we ask the user for two directories, one for the repo, and another for the installed stuff. It'd be best if MFEM installed the headers (in addition to the libs) if we ask for the miniapps, in which case the suggested change here would work in the general case.

**Comment by cmacmackin** [comment]
Would it be worth raising an issue in the MFEM repo?

**Comment by nmnobre** [comment]
I can ask Veselin on Slack if that's something they'd be willing to accept/merge and just create the PR if I get a positive answer. If I get a negative answer, however, it's easy to add a second variable here, e.g. `MFEM_REPO_DIR`, with default value `$(MFEM_DIR)/..`, what do you think?

**Pull request closed without merging**
